laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('imgfix', array( function(){
	$l = LazerImagem::all();
	$largura = 245;
	$altura = 245;
	foreach ($l as $a => $b) {
		if(file_exists(public_path().'assets/images/lazer/'.$b->imagem)){
			$imgobj = Image::make(public_path().'assets/images/lazer/'.$b->imagem);
			$ratio = $imgobj->width / $imgobj->height;
		  	$nratio = $largura / $altura;

			if ($ratio > $nratio) {
				$imgobj->resize(null, $altura, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			} else {
				$imgobj->resize($largura, null, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			}
			$imgobj->destroy();
		}
	}
	return "OK";
}));

// Rota da página inicial
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('suites', array('as' => 'suites', 'uses' => 'SuitesController@index'));
Route::get('suites/detalhes/{slug?}', array('as' => 'suites.detalhes', 'uses' => 'SuitesController@detalhes'));
Route::get('lazer', array('as' => 'lazer', 'uses' => 'LazerController@index'));
Route::get('promocoes', array('as' => 'promocoes', 'uses' => 'PromocoesController@index'));
Route::get('promocoes/detalhes/{slug?}', array('as' => 'promocoes.detalhes', 'uses' => 'PromocoesController@detalhes'));
Route::get('culinaria', array('as' => 'culinaria', 'uses' => 'CulinariaController@index'));
Route::get('mapa', array('as' => 'mapa', 'uses' => 'MapaController@index'));
Route::get('traslados', array('as' => 'traslados', 'uses' => 'TrasladosController@index'));
Route::get('reservas', array('as' => 'reservas', 'uses' => 'ReservasController@index'));
Route::get('cancelamento', array( function(){
	return View::make('frontend.reservas.cancelamento');
}));
Route::post('enviar', array('as' => 'reservas.enviar', 'uses' => 'ReservasController@enviar'));

// Rota da Home do painel
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
// Rota da Tela de Login
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

// Rota de Logout
Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::resource('banners', 'Painel\BannersController');
	Route::resource('suites', 'Painel\SuitesController');
	Route::resource('suitesImagens', 'Painel\SuitesImagensController');
	Route::resource('lazer', 'Painel\LazerController');
	Route::resource('lazerImagens', 'Painel\LazerImagensController');
	Route::resource('promocoes', 'Painel\PromocoesController');
    Route::resource('usuarios', 'Painel\UsuariosController');
});

laravel/app/controllers/painel/LazerImagens.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, File, Image, Lazer, LazerImagem;

class LazerImagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	public $limiteRegistros = 4;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$lazer_id = Input::get('lazer_id');

		if(!$lazer_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.lazerImagens.index')->with('registros', LazerImagem::orderBy('ordem', 'ASC')->where('lazer_id', $lazer_id)->get())
																  ->with('lazer', Lazer::find($lazer_id))
																  ->with('limiteRegistros', $this->limiteRegistros);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$lazer_id = Input::get('lazer_id');

		if(!$lazer_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.lazerImagens.form')->with('lazer', Lazer::find($lazer_id));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new LazerImagem;

		$object->legenda = Input::get('legenda');
		$object->lazer_id = Input::get('lazer_id');

		if(sizeof(LazerImagem::where('lazer_id', '=', $object->lazer_id)->get()) >= $this->limiteRegistros){
			Session::flash('formulario', array('legenda' => $object->legenda, 'lazer_id' => $object->lazer_id));
			return Redirect::back()->withErrors(array('Número máximo de imagens já atingido!'));
		}

		Thumb::make('imagem', 900, null, 'lazer/');
		$imagem = Thumb::make('imagem', 245, 245, 'lazer/thumbs/');
		if($imagem) $object->imagem = $imagem;
		
		if(!$object->imagem){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem de Lazer!'));
		}else{
			try {

				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Imagem de Lazer criada com sucesso.');
				return Redirect::route('painel.lazerImagens.index', array('lazer_id' => $object->lazer_id));

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Imagem de Lazer!'));	

			}
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$registro = LazerImagem::find($id);
		$lazer = Lazer::find($registro->lazer_id);
		$this->layout->content = View::make('backend.lazerImagens.edit')->with('registro', $registro)->with('lazer', $lazer);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = LazerImagem::find($id);

		$object->legenda = Input::get('legenda');
		$object->lazer_id = Input::get('lazer_id');

		Thumb::make('imagem', 900, null, 'lazer/');
		$imagem = Thumb::make('imagem', 245, 245, 'lazer/thumbs/');
		if($imagem) $object->imagem = $imagem;
		
		if(!$object->imagem){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem de Lazer!'));
		}else{
			try {

				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Imagem de Lazer alterada com sucesso.');
				return Redirect::route('painel.lazerImagens.index', array('lazer_id' => $object->lazer_id));

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Imagem de Lazer!'));	

			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$lazer_id = Input::get('lazer_id');

		$object = LazerImagem::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Imagem de Lazer removida com sucesso.');

		return Redirect::route('painel.lazerImagens.index', array('lazer_id' => $lazer_id));
	}

}

laravel/app/views/backend/lazerImagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Alterar Imagens de Lazer do Item: {{$lazer->id}}
        </h2>  
		
		{{ Form::open( array('route' => array('painel.lazerImagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" value="{{$registro->legenda}}" required>
				</div>

				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/lazer/thumbs/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>

				<input type="hidden" name="lazer_id" value="{{$lazer->id}}">

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.lazerImagens.index', array('lazer_id' => $lazer->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/lazerImagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Imagem de Lazer do Item: {{$lazer->titulo}}
        </h2>  

		<form action="{{URL::route('painel.lazerImagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); $s['legenda'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>

				<input type="hidden" name="lazer_id" value="{{$lazer->id}}">

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.lazerImagens.index', array('lazer_id' => $lazer->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/lazerImagens/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<a href="{{URL::route('painel.lazer.index')}}" title="Voltar para Lazer" class="btn btn-default">&larr; Voltar para Lazer</a>
	
	<h2>
  		Imagens de Lazer do Item: {{$lazer->titulo}} @if(sizeof($registros) < $limiteRegistros) <a href="{{ URL::route('painel.lazerImagens.create', array('lazer_id' => $lazer->id)) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Foto de Lazer</a> @endif
	</h2>

	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="lazer_imagens">
        
        <thead>
    		<tr>
	          	<th>Ordenar</th>
	          	<th>Legenda</th>
	          	<th>Imagem</th>
      			<th><span class="glyphicon glyphicon-cog"></span></th>
    		</tr>
  		</thead>

  		<tbody>
		@if(sizeof($registros))
	    	@foreach ($registros as $registro)

	        	<tr class="tr-row" id="row_{{ $registro->id }}">
	              	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-sm">mover</a></td>
	              	<td>{{$registro->legenda}}</td>
	              	<td><img src="assets/images/lazer/thumbs/{{$registro->imagem}}"></td>
	              	<td class="crud-actions">
	            		<a href="{{ URL::route('painel.lazerImagens.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	            	   {{ Form::open(array('route' => array('painel.lazerImagens.destroy', $registro->id), 'method' => 'delete')) }}
	                        <input type="hidden" name="lazer_id" value="{{$lazer->id}}">
	                        <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                   {{ Form::close() }}
	          		</td>
	        	</tr>

	    	@endforeach
		@else
			<tr><td colspan="4"><h3>Nenhum registro encontrado</h3></td></tr>
		@endif
  		</tbody>

    </table>
    
</div>

@stop