laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('imgfix', array( function(){
	$l = LazerImagem::all();
	$largura = 245;
	$altura = 245;
	foreach ($l as $a => $b) {
		if(file_exists(public_path().'assets/images/lazer/'.$b->imagem)){
			$imgobj = Image::make(public_path().'assets/images/lazer/'.$b->imagem);
			$ratio = $imgobj->width / $imgobj->height;
		  	$nratio = $largura / $altura;

			if ($ratio > $nratio) {
				$imgobj->resize(null, $altura, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			} else {
				$imgobj->resize($largura, null, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			}
			$imgobj->destroy();
		}
	}
	return "OK";
}));

// Rota da página inicial
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('suites', array('as' => 'suites', 'uses' => 'SuitesController@index'));
Route::get('suites/detalhes/{slug?}', array('as' => 'suites.detalhes', 'uses' => 'SuitesController@detalhes'));
Route::get('lazer', array('as' => 'lazer', 'uses' => 'LazerController@index'));
Route::get('promocoes', array('as' => 'promocoes', 'uses' => 'PromocoesController@index'));
Route::get('promocoes/detalhes/{slug?}', array('as' => 'promocoes.detalhes', 'uses' => 'PromocoesController@detalhes'));
Route::get('culinaria', array('as' => 'culinaria', 'uses' => 'CulinariaController@index'));
Route::get('mapa', array('as' => 'mapa', 'uses' => 'MapaController@index'));
Route::get('traslados', array('as' => 'traslados', 'uses' => 'TrasladosController@index'));
Route::get('reservas', array('as' => 'reservas', 'uses' => 'ReservasController@index'));
Route::get('cancelamento', array( function(){
	return View::make('frontend.reservas.cancelamento');
}));
Route::post('enviar', array('as' => 'reservas.enviar', 'uses' => 'ReservasController@enviar'));

// Rota da Home do painel
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
// Rota da Tela de Login
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

// Rota de Logout
Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::resource('banners', 'Painel\BannersController');
	Route::resource('suites', 'Painel\SuitesController');
	Route::resource('suitesImagens', 'Painel\SuitesImagensController');
	Route::resource('lazer', 'Painel\LazerController');
	Route::resource('lazerImagens', 'Painel\LazerImagensController');
	Route::resource('promocoes', 'Painel\PromocoesController');
    Route::resource('usuarios', 'Painel\UsuariosController');
});

laravel/app/views/backend/templates/index.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="no-js">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, nofollow" />
    <meta name="author" content="Trupe Design" />
    <meta name="copyright" content="2013 Trupe Design" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <title>Pedra Selada - Painel Administrativo</title>
	<meta name="description" content="">
    <meta name="keywords" content="" />
    
	<base href="{{ url() }}/">
	<script>var BASE = "{{ url() }}"</script>

	<?=Assets::CSS(array(
		'vendor/reset-css/reset',
		'css/fontface/stylesheet',
		'vendor/bootstrap/dist/css/bootstrap.min',
		'css/painel/base'
	))?>

	@if(isset($css))
		<?=Assets::CSS(array($css))?>
	@endif

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="assets/vendor/jquery/dist/jquery.min.js"><\/script>')</script>

	@if(App::environment()=='local')
		<?=Assets::JS(array('js/vendor/modernizr/modernizr', 'vendor/less.js/dist/less-1.6.2.min'))?>
	@else
		<?=Assets::JS(array('js/vendor/modernizr/modernizr'))?>
	@endif

</head>
	<body @if(Route::currentRouteName() == 'painel.login') class="body-painel-login" @else class="body-painel" @endif >

		@if(Route::currentRouteName() != 'painel.login')

			<nav class="navbar navbar-default">
				<div class="navbar-inner">
					<a href="{{URL::route('painel.home')}}" title="Página Inicial" class="navbar-brand">Pedra Selada</a>

					<ul class="nav navbar-nav">

						<li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.home')}}" title="Início">Início</a>
						</li>

						<li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.banners.index')}}" title="Banners">Banners</a>
						</li>

						<li @if(str_is('painel.suites*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.suites.index')}}" title="Suítes">Suítes</a>
						</li>

						<li @if(str_is('painel.lazer*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.lazer.index')}}" title="Lazer">Lazer</a>
						</li>

						<li @if(str_is('painel.promocoes*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.promocoes.index')}}" title="Promoções">Promoções</a>
						</li>

						<li class="dropdown">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.usuarios.index')}}" title="Usuários do Painel">Usuários</a></li>
								<li><a href="{{URL::route('painel.off')}}" title="Logout">Logout</a></li>
							</ul>
						</li>

					</ul>
				</div>
			</nav>

		@endif

		<div class="main {{ 'main-'.str_replace('.', '-', Route::currentRouteName()) }}">
			@yield('conteudo')
		</div>
		
		<footer>
			<div class="container">
				<a href="http://www.trupe.net" target="_blank" title="Criação de Sites : Trupe Agência Criativa">© Criação de Sites : Trupe Agência Criativa</a>
			</div>
		</footer>

		@if(Route::currentRouteName() == 'painel.login')
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/login'
			))?>
		@else
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/painel'
			))?>
		@endif

	</body>
</html>