laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('imgfix', array( function(){
	$l = LazerImagem::all();
	$largura = 245;
	$altura = 245;
	foreach ($l as $a => $b) {
		if(file_exists(public_path().'assets/images/lazer/'.$b->imagem)){
			$imgobj = Image::make(public_path().'assets/images/lazer/'.$b->imagem);
			$ratio = $imgobj->width / $imgobj->height;
		  	$nratio = $largura / $altura;

			if ($ratio > $nratio) {
				$imgobj->resize(null, $altura, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			} else {
				$imgobj->resize($largura, null, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			}
			$imgobj->destroy();
		}
	}
	return "OK";
}));

// Rota da página inicial
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('suites', array('as' => 'suites', 'uses' => 'SuitesController@index'));
Route::get('suites/detalhes/{slug?}', array('as' => 'suites.detalhes', 'uses' => 'SuitesController@detalhes'));
Route::get('lazer', array('as' => 'lazer', 'uses' => 'LazerController@index'));
Route::get('promocoes', array('as' => 'promocoes', 'uses' => 'PromocoesController@index'));
Route::get('promocoes/detalhes/{slug?}', array('as' => 'promocoes.detalhes', 'uses' => 'PromocoesController@detalhes'));
Route::get('culinaria', array('as' => 'culinaria', 'uses' => 'CulinariaController@index'));
Route::get('mapa', array('as' => 'mapa', 'uses' => 'MapaController@index'));
Route::get('traslados', array('as' => 'traslados', 'uses' => 'TrasladosController@index'));
Route::get('reservas', array('as' => 'reservas', 'uses' => 'ReservasController@index'));
Route::get('cancelamento', array( function(){
	return View::make('frontend.reservas.cancelamento');
}));
Route::post('enviar', array('as' => 'reservas.enviar', 'uses' => 'ReservasController@enviar'));

// Rota da Home do painel
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
// Rota da Tela de Login
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

// Rota de Logout
Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::resource('banners', 'Painel\BannersController');
	Route::resource('suites', 'Painel\SuitesController');
	Route::resource('suitesImagens', 'Painel\SuitesImagensController');
	Route::resource('lazer', 'Painel\LazerController');
	Route::resource('lazerImagens', 'Painel\LazerImagensController');
	Route::resource('promocoes', 'Painel\PromocoesController');
    Route::resource('usuarios', 'Painel\UsuariosController');
});

laravel/app/models/Lazer.php
<?php

class Lazer extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'lazer';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    protected function imagens(){
    	return $this->hasMany('LazerImagem', 'lazer_id');
    }
}

laravel/app/controllers/LazerController.php
<?php

use \Lazer;

class LazerController extends BaseController {

	public function index()
	{
		$this->layout->with('titulo', 'Lazer');
		$this->layout->content = View::make('frontend.lazer.index')->with('itemsLazer', Lazer::orderBy('ordem', 'asc')->get());
	}

}

laravel/app/controllers/painel/LazerController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, File, Image, Lazer;

class LazerController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.lazer.index')->with('registros', Lazer::orderBy('ordem', 'ASC')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.lazer.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Lazer;

		$object->titulo = Input::get('titulo');

		if(!$object->titulo){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Item de Lazer!'));
		}else{
			try {

				$object->save();

				$object->slug = Str::slug($object->id.'_'.$object->titulo);
				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Item de Lazer criado com sucesso.');
				return Redirect::route('painel.lazer.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Item de Lazer!'));	

			}
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.lazer.edit')->with('registro', Lazer::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Lazer::find($id);

		$object->titulo = Input::get('titulo');
		
		if(!$object->titulo){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Item de Lazer!'));
		}else{
			try {

				$object->save();

				$object->slug = Str::slug($object->id.'_'.$object->titulo);
				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Item de Lazer alterado com sucesso.');
				return Redirect::route('painel.lazer.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(array('Erro ao criar Item de Lazer!'));	

			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Lazer::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Item de Lazer removido com sucesso.');

		return Redirect::route('painel.lazer.index');
	}

}

laravel/app/views/backend/lazer/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Alterar Item de Lazer
        </h2>  
		
		{{ Form::open( array('route' => array('painel.lazer.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputTitulo">Título</label>
					<input type="text" class="form-control" id="inputTitulo" name="titulo" value="{{ $registro->titulo }}" required>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.lazer.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/lazer/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Item de Lazer
        </h2>  

		<form action="{{URL::route('painel.lazer.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputTitulo">Título</label>
					<input type="text" class="form-control" id="inputTitulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); $s['titulo'] }}" @endif required>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.lazer.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/lazer/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<h2>
  		Lazer <a href="{{ URL::route('painel.lazer.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Item de Lazer</a>
	</h2>
	
	<div class="alert alert-block alert-info" style="text-align:center">
		Somente os itens com imagens associadas serão exibidos no site.
	</div>

	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="lazer">
        
        <thead>
    		<tr>
	          	<th>Ordenar</th>
	          	<th>Título</th>
	          	<th>Imagens</th>
      			<th><span class="glyphicon glyphicon-cog"></span></th>
    		</tr>
  		</thead>

  		<tbody>
		@if(sizeof($registros))
	    	@foreach ($registros as $registro)

	        	<tr class="tr-row" id="row_{{ $registro->id }}">
	              	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-sm">mover</a></td>
	              	<td>{{$registro->titulo}}</td>
	              	<td><a href="{{URL::route('painel.lazerImagens.index', array('lazer_id' => $registro->id))}}" class="btn btn-sm btn-default" title="Gerenciar imagens do item: {{$registro->titulo}}">gerenciar</a></td>
	              	<td class="crud-actions">
	            		<a href="{{ URL::route('painel.lazer.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	            	   {{ Form::open(array('route' => array('painel.lazer.destroy', $registro->id), 'method' => 'delete')) }}
	                        <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                   {{ Form::close() }}
	          		</td>
	        	</tr>

	    	@endforeach
		@else
			<tr><td colspan="4"><h3>Nenhum registro encontrado</h3></td></tr>
		@endif
  		</tbody>

    </table>
    
</div>

@stop