laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('imgfix', array( function(){
	$l = LazerImagem::all();
	$largura = 245;
	$altura = 245;
	foreach ($l as $a => $b) {
		if(file_exists(public_path().'assets/images/lazer/'.$b->imagem)){
			$imgobj = Image::make(public_path().'assets/images/lazer/'.$b->imagem);
			$ratio = $imgobj->width / $imgobj->height;
		  	$nratio = $largura / $altura;

			if ($ratio > $nratio) {
				$imgobj->resize(null, $altura, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			} else {
				$imgobj->resize($largura, null, true, false)->resizeCanvas($largura, $altura, 'center', false, '#FFFFFF')->save(public_path().'assets/images/lazer/thumbs/'.$b->imagem, 100);
			}
			$imgobj->destroy();
		}
	}
	return "OK";
}));

// Rota da página inicial
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('suites', array('as' => 'suites', 'uses' => 'SuitesController@index'));
Route::get('suites/detalhes/{slug?}', array('as' => 'suites.detalhes', 'uses' => 'SuitesController@detalhes'));
Route::get('lazer', array('as' => 'lazer', 'uses' => 'LazerController@index'));
Route::get('promocoes', array('as' => 'promocoes', 'uses' => 'PromocoesController@index'));
Route::get('promocoes/detalhes/{slug?}', array('as' => 'promocoes.detalhes', 'uses' => 'PromocoesController@detalhes'));
Route::get('culinaria', array('as' => 'culinaria', 'uses' => 'CulinariaController@index'));
Route::get('mapa', array('as' => 'mapa', 'uses' => 'MapaController@index'));
Route::get('traslados', array('as' => 'traslados', 'uses' => 'TrasladosController@index'));
Route::get('reservas', array('as' => 'reservas', 'uses' => 'ReservasController@index'));
Route::get('cancelamento', array( function(){
	return View::make('frontend.reservas.cancelamento');
}));
Route::post('enviar', array('as' => 'reservas.enviar', 'uses' => 'ReservasController@enviar'));

// Rota da Home do painel
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
// Rota da Tela de Login
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

// Rota de Logout
Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::resource('banners', 'Painel\BannersController');
	Route::resource('suites', 'Painel\SuitesController');
	Route::resource('suitesImagens', 'Painel\SuitesImagensController');
	Route::resource('lazer', 'Painel\LazerController');
	Route::resource('lazerImagens', 'Painel\LazerImagensController');
	Route::resource('promocoes', 'Painel\PromocoesController');
    Route::resource('usuarios', 'Painel\UsuariosController');
});

laravel/app/views/backend/suitesImagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Alterar Imagem da Suíte: {{$suite->titulo}}
        </h2>  
		
		{{ Form::open( array('route' => array('painel.suitesImagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" value="{{ $registro->legenda }}" required>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					@if($registro->imagem)
						<br><img src="assets/images/suites/imagens/thumbs/{{$registro->imagem}}"><br><br>
					@endif
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div><br>

				<input type="hidden" name="id_suite" value="{{$suite->id}}">

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.suitesImagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/suitesImagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Imagem da Suíte: {{$suite->titulo}}
        </h2>  

		<form action="{{URL::route('painel.suitesImagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); $s['legenda'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>

				<input type="hidden" name="id_suite" value="{{$suite->id}}">

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.suitesImagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/suitesImagens/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<a href="{{URL::route('painel.suites.index')}}" title="Voltar para as Suítes" class="btn btn-default btn-sm">&larr; Voltar para Suítes</a>

	<h2>
  		Imagens da Suíte: {{$suite->titulo}} <a href="{{ URL::route('painel.suitesImagens.create', array('id_suite' => $suite->id)) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Imagem</a>
	</h2>


	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="suites_imagens">
        
        <thead>
    		<tr>
	          	<th>Ordenar</th>
	          	<th>Imagem</th>
	          	<th>Legenda</th>
      			<th><span class="glyphicon glyphicon-cog"></span></th>
    		</tr>
  		</thead>

  		<tbody>
		@if(sizeof($registros))
	    	@foreach ($registros as $registro)

	        	<tr class="tr-row" id="row_{{ $registro->id }}">
	              	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-sm">mover</a></td>
	              	<td><img src="assets/images/suites/imagens/thumbs/{{$registro->imagem}}"></td>
	              	<td>{{ Str::words($registro->legenda, 15) }}</td>
	              	<td class="crud-actions">
	            		<a href="{{ URL::route('painel.suitesImagens.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	            	   {{ Form::open(array('route' => array('painel.suitesImagens.destroy', $registro->id), 'method' => 'delete')) }}
	                        <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                   {{ Form::close() }}
	          		</td>
	        	</tr>

	    	@endforeach
		@else
			<tr><td colspan="4"><h3>Nenhum registro encontrado</h3></td></tr>
		@endif
  		</tbody>

    </table>
    
</div>

@stop